### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

### ISSUE THREAD

**Issue by Milozms** [facebookresearch/UnsupervisedQA#13]
I correctly installed all the requirements following readme. but I med the error when I ran the program:

> Traceback (most recent call last):
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 19, in <module>
    from .constituency_parsing import get_constituency_parsed_clozes, shorten_cloze
  File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/constituency_parsing.py", line 12, in <module>
    from allennlp.models.archival import load_archive
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/models/__init__.py", line 8, in <module>
    from allennlp.models.biattentive_classification_network import BiattentiveClassificationNetwork
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/models/biattentive_classification_network.py", line 16, in <module>
    from allennlp.training.metrics import CategoricalAccuracy
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/training/metrics/__init__.py", line 11, in <module>
    from allennlp.training.metrics.conll_coref_scores import ConllCorefScores
  File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/training/metrics/conll_coref_scores.py", line 5, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'
[INFO/MainProcess] process shutting down

**Comment by patrick-s-h-lewis** [comment]
Looks like allennlp has a missing sklearn dependency.
have you tried installing sklearn manually?

**Comment by Milozms** [comment]
ok, I fixed it.  I tried manually installed sklearn previously but it didn't work.  After I removed numpy, reinstalled numpy with "conda install" and then install sklearn, it started running.

But i met another error:

> Traceback (most recent call last):
  File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
>     chunked=chunked,
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
>     self._validate_conn(conn)
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
>     conn.connect()
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
>     conn = self._new_conn()
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
>     self, "Failed to establish a new connection: %s" % e
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x11ee4b150>: Failed to establish a new connection: [Errno 60] Operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/Users/zms/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11ee4b150>: Failed to establish a new connection: [Errno 60] Operation timed out'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 165, in <module>
>     generate_synthetic_training_data(args)
>   File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 102, in generate_synthetic_training_data
>     clozes = [short_cloze for cloze in syntax_clozes for short_cloze in shorten_cloze(cloze)]
>   File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 102, in <listcomp>
>     clozes = [short_cloze for cloze in syntax_clozes for short_cloze in shorten_cloze(cloze)]
>   File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/constituency_parsing.py", line 28, in get_constituency_parsed_clozes
>     predictor = _load_constituency_parser()
>   File "/Users/zms/Documents/Study/NLP/UnsupervisedQA/unsupervisedqa/constituency_parsing.py", line 22, in _load_constituency_parser
>     archive = load_archive(CONSTITUENCY_MODEL, cuda_device=CONSTITUENCY_CUDA)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/models/archival.py", line 105, in load_archive
>     resolved_archive_file = cached_path(archive_file)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 86, in cached_path
>     return get_from_cache(url_or_filename, cache_dir)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 174, in get_from_cache
>     response = requests.head(url, allow_redirects=True)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/api.py", line 104, in head
>     return request('head', url, **kwargs)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/zms/anaconda3/envs/uqa37/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11ee4b150>: Failed to establish a new connection: [Errno 60] Operation timed out'))
> [INFO/MainProcess] process shutting down

is that caused by the network connection?

**Comment by patrick-s-h-lewis** [comment]
Requests is throwing an connection error when allen_nlp tries to download the parser. This isnt a UnsupervisedQA specific issue, so closing.

**Comment by karthik19967829** [comment]
try installing scikit-learn through pip install scikit-learn==0.22.2 . It fixed the issue in my case

**Comment by hi-one-gg** [comment]
> try installing scikit-learn through pip install scikit-learn==0.22.2 . It fixed the issue in my case

Yes! it works! : )

**Comment by sunfeng90** [comment]
> > try installing scikit-learn through pip install scikit-learn==0.22.2 . It fixed the issue in my case
> 
> Yes! it works! : )

It works for me.

**Comment by 84210maruf** [comment]
Everything is possible you can do it buddy!
