### ISSUE TITLE
While running this code on different dataset of paragraphs

### ISSUE THREAD

**Issue by yugaljain1999** [facebookresearch/UnsupervisedQA#14]
I have dataset of 20,000 research articles, how can I generate synthetic question-answer dataset from these articles?
This dataset is completely different from SQUAD dataset used here in this code.
Thanks!

**Comment by yugaljain1999** [comment]
@patrick-s-h-lewis @likethesky please reply as I am working on important project and struggling since so many days.
Thanks!

**Comment by patrick-s-h-lewis** [comment]
Dear Yugal,

Github issues are generally for when there is a specific issue with the code, bugs etc. 
Your question is super general. 
The readme has all the info you need to run the code. https://github.com/facebookresearch/UnsupervisedQA#usage

Patrick

**Comment by yugaljain1999** [comment]
@patrick-s-h-lewis, Thanks for your reply, actually  I wanted to  ask..if I load COVID-19 research articles (instead of English wikipedia articles) as an `example_input.txt` file  , then  can this code generate synthetic question-answer pairs for these articles by running this command `python -m unsupervisedqa.generate_synthetic_qa_data example_input.txt example_output \
    --input_file_format "txt" \
    --output_file_format "jsonl,squad" \
    --translation_method unmt \
    --use_named_entity_clozes \
    --use_subclause_clozes \
    --use_wh_heuristic `  where example_input.txt is  dataset on "COVID-19 research articles"?

I have asked this because vocabulary you used is trained on English wikipedia articles, so is this possible to generate question-answer pairs based on COVID-19 research articles which has different vocabulary?

Is there is any method or code to fine-tune this Unsupervised QA-model on COVID-19 research articles dataset?

Thanks!
