### ISSUE TITLE
AssertionError: mismatch between number of clozes and translations

### ISSUE THREAD

**Issue by aarav98** [facebookresearch/UnsupervisedQA#16]
I am failing to understand why I am encoutering this issue with many paragraphs in my dataset. My dataset is set of pages in certain category from wikipedia. 

Following is an example paragraph.
_{"text": "As the flat spring moves, the force from the curved spring increases. This results in acceleration until the normally-closed contacts are hit. Just as in the downward direction, the switch is designed so that the curved spring is strong enough to move the contacts, even if the flat spring must flex, because the actuator does not move during the changeover. ==Applications==\nMicroswitches have two main areas of application:\nFirstly they are used when a low operating force with a clearly defined action is needed. Secondly they are used when long-term reliability is needed.", "paragraph_id": "ee63d5c3-38f9-44c6-a3e7-dcccfeacfbb1"}_

Following are the intermediate outputs for clozes and translations.

_Cloze Size: 3
[Cloze(cloze_id='18e074b67a5d4424e328bd68b4d5ef32270df1e2_0', paragraph=Paragraph(paragraph_id='ee63d5c3-38f9-44c6-a3e7-dcccfeacfbb1', text='As the flat spring moves, the force from the curved spring increases. This results in acceleration until the normally-closed contacts are hit. Just as in the downward direction, the switch is designed so that the curved spring is strong enough to move the contacts, even if the flat spring must flex, because the actuator does not move during the changeover. ==Applications==\nMicroswitches have two main areas of application:\nFirstly they are  used when a low operating force with a clearly defined action is needed. Secondly they are used when long-term reliability is needed.'), source_text='=Applications==\nMicroswitches have two main areas of application', source_start=360, cloze_text='=Applications==\nIDENTITYMASK have two main areas of application', answer_text='Microswitches', answer_start=16, constituency_parse=None, root_label=None, answer_type='ORG', question_text=None), Cloze(cloze_id='718e5f5bdc5cd0fe4c27ca36b4bb0d416d06e178_0', paragraph=Paragraph(paragraph_id='ee63d5c3-38f9-44c6-a3e7-dcccfeacfbb1', text='As the flat spring moves, the force from the curved spring increases. This results in acceleration until the normally-closed contacts are hit. Just as in the downward direction, the switch is designed so that the curved spring is strong enough to move the contacts, even if the flat spring must flex, because the actuator does not move during the chang                                            eover. ==Applications==\nMicroswitches have two main areas of application:\nFirstly they are used when a low operatin                                            g force with a clearly defined action is needed. Secondly they are used when long-term reliability is needed.'), sour                                            ce_text='=Applications==\nMicroswitches have two main areas of application', source_start=360, cloze_text='=Applicati                                            ons==\nMicroswitches have NUMERICMASK main areas of application', answer_text='two', answer_start=35, constituency_pa                                            rse=None, root_label=None, answer_type='CARDINAL', question_text=None), Cloze(cloze_id='7ae37543efcc853a4c1b53007fe82                                            6fb622afff5_0', paragraph=Paragraph(paragraph_id='ee63d5c3-38f9-44c6-a3e7-dcccfeacfbb1', text='As the flat spring moves, the force from the curved spring increases. This results in acceleration until the normally-closed contacts are hit. Just as in the downward direction, the switch is designed so that the curved spring is strong enough to move the  contacts, even if the flat spring must flex, because the actuator does not move during the changeover. ==Applications ==\nMicroswitches have two main areas of application:\nFirstly they are used when a low operating force with a clearly defined action is needed. Secondly they are used when long-term reliability is needed.'), source_text='Firstly they are used when a low operating force with a clearly defined action is needed', source_start=426, cloze_text='NUMERICMASK they are used when a low operating force with a clearly defined action is needed', answer_text='Firstly', answer_start=0, constituency_parse=None, root_label=None, answer_type='ORDINAL', question_text=None)]_

_Translation Size: 5
['Who = Applications = ?', 'When you have two main areas of application ?', 'How much = Applications = ?', 'What are the main Microswitches areas of application ?', 'How many times are they used when a low operating force with a clear                                            ly defined action is needed ?']_

Could someone please explain what causes to generate different number of clozes and translations and how that can be fixed?

I am using the following parameters:
python -m unsupervisedqa.generate_synthetic_qa_data example_input.txt example_output \
    --input_file_format "jsonl" \
    --output_file_format "jsonl" \
    --translation_method unmt \
    --use_named_entity_clozes \
    --use_subclause_clozes \
    --use_wh_heuristic

**Comment by aarav98** [comment]
Could one of the contributors please provide some information on this issue. I have tried to lto debugg the code but I didn't understand why the number of clozes and translations are different.

**Comment by patrick-s-h-lewis** [comment]
Try removing the newlines from the input?

**Comment by patrick-s-h-lewis** [comment]
Also, things like section titles etc are likely to confuse the models. 
Try cleaning the input data by removing them.

(as an aside, what is your use-case? if you want to generate questions and answers from wikipedia paragraphs, there are supervised datasets available which will give much better results - unless there is a special requirement for a strict "unsupervised" approach, this codebase probably isn't the right choice).

**Comment by aarav98** [comment]
Could you please point me to one of such supervised approaches.

**Comment by aarav98** [comment]
> Also, things like section titles etc are likely to confuse the models.
> Try cleaning the input data by removing them.
> 
> (as an aside, what is your use-case? if you want to generate questions and answers from wikipedia paragraphs, there are supervised datasets available which will give much better results - unless there is a special requirement for a strict "unsupervised" approach, this codebase probably isn't the right choice).

Thank you for the answer! Mor data cleaning helped resolved the issues.
