### ISSUE TITLE
Other license at some point?

### ISSUE THREAD

**Issue by roschler** [facebookresearch/UnsupervisedQA#2]
Will this project ever be released under a more liberal license that permits potential commercial usage like the other Facebook research projects I've looked at do: MIT, BSD, Apache, etc.?  Currently this project is under the Creative Commons license variant that does not allow commercial usage.

https://github.com/facebookresearch/UnsupervisedQA/blob/master/LICENSE

**Comment by patrick-s-h-lewis** [comment]
Hi @roschler. Thanks for your interest - I'll investigate whether other licensing options may be available, but this may take some time and I cant guarantee we'll be able to change the license
