### ISSUE TITLE
Codes for rule-based question generation described in the paper

### ISSUE THREAD

**Issue by shmsw25** [facebookresearch/UnsupervisedQA#8]
Hi @patrick-s-h-lewis, thanks for the nice paper and open-sourcing the code. It is really helpful.

I see that you've mentioned in the paper about rule-based systems (Heilman & Smith 2010) and there is an off-the-shelf tool for English. Do you have any plan to release the code to run it, or would you give a pointer to the off-the-shelf tool that you used? I'd really appreciate it!

**Comment by patrick-s-h-lewis** [comment]
Hey Sewon!

Yep, so the code for the rulebased system is available from the orginal authors here: http://www.cs.cmu.edu/~ark/mheilman/questions/

it can be run with e.g.:

```
cat input.txt | java -Xmx1400m -cp question-generation.jar \
	edu/cmu/ark/QuestionAsker \
	--verbose --model models/linear-regression-ranker-reg500.ser.gz \
	--just-wh --max-length 30 --downweight-pro > output.txt
```

**Comment by shmsw25** [comment]
This is exactly what I was looking for! Thanks a lot for your help.
